name: WebRtcSIR
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_webrtc: 0.9.27
  flutter_foreground_task: ^6.1.3
  flutter_background: ^1.2.0
  get_it: ^7.2.0
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  flutter_facebook_auth: ^5.0.8
  uuid: ^3.0.6
  appwrite: ^12.0.3
  socket_io_client: ^2.0.3+1
  device_info_plus: ^10.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true
