// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzKLmaU6iytuDuHKnzv8LycEVBoqPfGXI',
    appId: '1:142599186501:web:4d62e5a85a378696f2db2c',
    messagingSenderId: '142599186501',
    projectId: 'test-tap-f2390',
    authDomain: 'test-tap-f2390.firebaseapp.com',
    storageBucket: 'test-tap-f2390.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWrlrMDWEDnmlEFW1Gg-0uxSBMme_9ZBU',
    appId: '1:142599186501:android:72f5423d7f918405f2db2c',
    messagingSenderId: '142599186501',
    projectId: 'test-tap-f2390',
    storageBucket: 'test-tap-f2390.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLjYcVFJvUueYXFjSKNyRcStQ6cVDHjW0',
    appId: '1:142599186501:ios:5136f10ce5315437f2db2c',
    messagingSenderId: '142599186501',
    projectId: 'test-tap-f2390',
    storageBucket: 'test-tap-f2390.appspot.com',
    iosBundleId: 'com.example.testTup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLjYcVFJvUueYXFjSKNyRcStQ6cVDHjW0',
    appId: '1:142599186501:ios:5136f10ce5315437f2db2c',
    messagingSenderId: '142599186501',
    projectId: 'test-tap-f2390',
    storageBucket: 'test-tap-f2390.appspot.com',
    iosBundleId: 'com.example.testTup',
  );
}
